// Core Utility Hooks
export * from './useAsync';
export * from './useBattery';
export * from './useClickOutside';
export * from './useClipboard';
export * from './useDebounce';
export * from './useDocumentTitle';
export * from './useEventListener';
export * from './useFetch';
export * from './useForm';
export * from './useFullscreen';
export * from './useGeolocation';
export * from './useHistory';
export * from './useHotkeys';
export * from './useHover';
export * from './useIdle';
export * from './useIntersectionObserver';
export * from './useInterval';
export * from './useKeyPress';
export * from './useLocalStorage';
export * from './useMeasure';
export * from './useMediaQuery';
export * from './useMediaStream';
export * from './useModal';
export * from './useMount';
export * from './useMousePosition';
export * from './useNetwork';
export * from './useOnlineStatus';
export * from './usePagination';
export * from './usePrevious';
export * from './useRaf';
export * from './useRateLimit';
export * from './useSanitizedInput';
export * from './useScript';
export * from './useScroll';
export * from './useSortableData';
export * from './useSound';
export * from './useSpeechRecognition';
export * from './useSpeechSynthesis';
export * from './useThrottle';
export * from './useTimeout';
export * from './useToast';
export * from './useToggle';
export * from './useUnmount';
export * from './useUpdateEffect';
export * from './useWebWorker';
export * from './useWindowSize';

// AI Hooks
export * from './useAICosts';
export * from './useAIFineTuning';
export * from './useAIIntelligence';
export * from './useAIModelRouting';
export * from './useAIPlayground';
export * from './useAIUsageAnalytics';
export { useChat, type Message as ChatMessage } from './useChat';

// CRM Hooks
export * from './useCRMAnalytics';
export * from './useCRMAssignments';
export * from './useCRMContacts';
export * from './useCRMDeals';
export * from './useCRMEmails';

// Data Hooks
export * from './useApiError';
export * from './useDashboardData';
export * from './useDataQuery';
export * from './useFeedback';
export * from './useFileStorage';
export * from './useFileUpload';
export * from './useGamification';
export * from './useKeyboardShortcuts';
export * from './useMarketingRealtime';
export { useMessages, type Message as ConversationMessage } from './useMessages';
export * from './useNotifications';

// Service Hooks (Production)
export { useGrades } from './useGrades';
export { useAttendance } from './useAttendance';
export * from './useOwnerAnalytics';
export * from './useOwnerDashboard';
export * from './usePhase2Data';
export * from './usePlatformSettings';
export * from './usePocketBase';
export * from './useSystemAlerts';
export * from './useTenantMetrics';
export * from './useRealtime';
export * from './useSchoolDashboard';
export * from './useChurnPrediction';
export * from './useExportCenter';
export * from './useDashboardBuilder';
export * from './useCompliance';
export * from './useTenantCloning';
export * from './useABTesting';
export * from './useIncidentResponse';
export * from './useComparativeAnalytics';
export * from './useFeatureUsage';
export * from './useTenantNotifications';
export * from './useRateLimiting';
export * from './useTenantHealth';
export * from './useAdvancedSearch';
export * from './useImportExport';
export * from './useBillingRules';
export * from './useOnboarding';
export * from './useUserMerge';
export * from './useBulkOperations';
export * from './useSecurityAuditLog';
export * from './usePenetrationTest';
export * from './useTenantUsageReports';
export * from './useAPIKeyManagement';
export * from './useWebhookConfiguration';
export * from './useUserProfile';
export * from './useValidation';
